services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - "3307:3307"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - ./src:/app
    ports:
      - "3001:3001"
    depends_on:
      - db

volumes:
  mysql_data:
